import { buildAvatarUrl, formatLastUpdatedAt } from './utils/taskUtils'

/** @type {import('./types.js').Task[]} */
export const SEED_TASKS = [
  {
    id: 'tsk-001',
    projectId: '1',
    projectName: 'Immeuble Atlas',
    nom: 'Validation plans architecte',
    responsable: {
      name: 'Sara Benali',
      avatarUrl: buildAvatarUrl('Sara Benali'),
    },
    statut: 'en_cours',
    echeance: '2026-06-18',
    priorite: 'haute',
    budget: 45000,
    fichiers: ['plans-v3.pdf', 'devis-materiaux.xlsx'],
    notes: 'En attente retour bureau d\'études structure.',
    lastUpdatedBy: 'Sara Benali',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-16T12:30:00')),
  },
  {
    id: 'tsk-002',
    projectId: '2',
    projectName: 'Chantier Marina',
    nom: 'Commande ciment & acier',
    responsable: {
      name: 'Karim El Amrani',
      avatarUrl: buildAvatarUrl('Karim El Amrani'),
    },
    statut: 'termine',
    echeance: '2026-06-10',
    priorite: 'moyenne',
    budget: 128500,
    fichiers: ['bon-commande.pdf'],
    notes: 'Livraison confirmée pour le 12 juin.',
    lastUpdatedBy: 'Karim El Amrani',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-15T09:00:00')),
  },
  {
    id: 'tsk-003',
    projectId: '1',
    projectName: 'Immeuble Atlas',
    nom: 'Inspection sécurité échafaudage',
    responsable: {
      name: 'Nadia Ouarzazi',
      avatarUrl: buildAvatarUrl('Nadia Ouarzazi'),
    },
    statut: 'bloque',
    echeance: '2026-06-14',
    priorite: 'haute',
    budget: 8500,
    fichiers: ['checklist-securite.pdf', 'photos-chantier.zip'],
    notes: 'Bloqué — inspecteur indisponible cette semaine.',
    lastUpdatedBy: 'Nadia Ouarzazi',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-16T10:00:00')),
  },
  {
    id: 'tsk-004',
    projectId: '3',
    projectName: 'Résidence Palm',
    nom: 'Réunion coordination sous-traitants',
    responsable: {
      name: 'Youssef Idrissi',
      avatarUrl: buildAvatarUrl('Youssef Idrissi'),
    },
    statut: 'non_commence',
    echeance: '2026-06-22',
    priorite: 'basse',
    budget: 0,
    fichiers: [],
    notes: 'Préparer ordre du jour et liste participants.',
    lastUpdatedBy: 'Youssef Idrissi',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-13T16:00:00')),
  },
  {
    id: 'tsk-005',
    projectId: '3',
    projectName: 'Résidence Palm',
    nom: 'Facturation acompte client',
    responsable: {
      name: 'Sara Benali',
      avatarUrl: buildAvatarUrl('Sara Benali'),
    },
    statut: 'en_cours',
    echeance: '2026-06-16',
    priorite: 'moyenne',
    budget: 92000,
    fichiers: ['facture-acompte.pdf', 'pv-reception.docx'],
    notes: 'Vérifier montant avec comptabilité avant envoi.',
    lastUpdatedBy: 'Administrateur',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-16T14:30:00')),
  },
  {
    id: 'tsk-006',
    projectId: '2',
    projectName: 'Chantier Marina',
    nom: 'Pose menuiserie aluminium — Bloc B',
    responsable: {
      name: 'Karim El Amrani',
      avatarUrl: buildAvatarUrl('Karim El Amrani'),
    },
    statut: 'non_commence',
    echeance: '2026-06-25',
    priorite: 'moyenne',
    budget: 67300,
    fichiers: ['cahier-des-charges.pdf'],
    notes: 'Matériaux en stock, équipe disponible semaine 26.',
    lastUpdatedBy: 'Karim El Amrani',
    lastUpdatedAt: formatLastUpdatedAt(new Date('2026-06-11T11:00:00')),
  },
]
